#!/usr/bin/env node
/**
 * sync_portfolio.js — Sync portfolio content from canonical JSON into the React project.
 *
 * Writes a TypeScript/JavaScript module the rest of the app imports from.
 * This keeps `data/portfolio_content.json` as the single source of truth.
 *
 * Usage:
 *   node scripts/sync_portfolio.js                        # default: writes to src/data/portfolio.ts
 *   node scripts/sync_portfolio.js --out src/data/portfolio.js   # use JS instead of TS
 *   node scripts/sync_portfolio.js --target ../my-portfolio      # target a different project root
 *
 * Run this after editing data/portfolio_content.json. The React app picks up the new data on next reload.
 */

const fs = require('fs');
const path = require('path');

// ---------- args ----------
const args = process.argv.slice(2);
const getArg = (flag, def) => {
  const i = args.indexOf(flag);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : def;
};

const SKILL_ROOT = path.resolve(__dirname, '..');
const target = path.resolve(getArg('--target', process.cwd()));
const outRel = getArg('--out', 'src/data/portfolio.ts');
const outPath = path.join(target, outRel);
const dataPath = path.join(SKILL_ROOT, 'data', 'portfolio_content.json');

// ---------- load ----------
if (!fs.existsSync(dataPath)) {
  console.error(`✗ Data file missing: ${dataPath}`);
  process.exit(1);
}
const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

// ---------- generate module ----------
const isTs = outPath.endsWith('.ts') || outPath.endsWith('.tsx');

const typeDefs = `
export interface Identity {
  name: string;
  handle: string;
  tagline: string;
  location: string;
  status: string;
  email: string;
  phone: string;
  links: Record<string, string>;
}

export interface Hero {
  title: string;
  subtitle: string;
  pillars: string[];
  intro: string;
}

export interface About {
  summary: string[];
}

export interface StackGroup {
  category: string;
  items: string[];
}

export interface Experience {
  id: string;
  role: string;
  company: string;
  location: string;
  period: string;
  summary: string;
  highlights: string[];
  stack: string[];
}

export interface Project {
  id: string;
  name: string;
  tagline: string;
  description: string;
  stack: string[];
  role: string;
  status: 'production' | 'personal' | 'wip';
  links: Record<string, string>;
}

export interface Education {
  title: string;
  institution: string;
  period: string;
}

export interface Language {
  name: string;
  level: string;
}

export interface PortfolioContent {
  identity: Identity;
  hero: Hero;
  about: About;
  stack: StackGroup[];
  experience: Experience[];
  projects: Project[];
  education: Education[];
  languages: Language[];
}
`;

const banner = `/**
 * AUTO-GENERATED by vuk-portfolio skill.
 * Source: vuk-portfolio/data/portfolio_content.json
 *
 * DO NOT EDIT THIS FILE BY HAND.
 * To update, edit the source JSON and run \`node scripts/sync_portfolio.js\`.
 *
 * Generated: ${new Date().toISOString()}
 */
`;

let body;
if (isTs) {
  body = `${banner}
${typeDefs}

export const portfolio: PortfolioContent = ${JSON.stringify(data, null, 2)} as const;

export default portfolio;
`;
} else {
  body = `${banner}
export const portfolio = ${JSON.stringify(data, null, 2)};

export default portfolio;
`;
}

// ---------- write ----------
const outDir = path.dirname(outPath);
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, body, 'utf-8');

console.log(`✓ Portfolio data synced`);
console.log(`  Source: ${path.relative(process.cwd(), dataPath)}`);
console.log(`  Output: ${path.relative(process.cwd(), outPath)}`);
console.log(``);
console.log(`Next: import { portfolio } from "${outRel.replace(/\.[tj]sx?$/, '')}";`);
